default: &default
  adapter: postgresql
  encoding: utf-8
  template: template0
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backbone_app_development
  username: 'backbone_app'
  password: 'postgres'
  host: 'localhost'
  port: 5432

test:
  <<: *default
  database: backbone_app_test

production:
  <<: *default
  database: backbone_app_production
  username: backbone_app
  password: <%= ENV['BACKBONE_APP_DATABASE_PASSWORD'] %>
